spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.23.16:3306/jpatest
    username: root
    password: root
    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      multiTenancy: database

server:
  port: 8081