spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.50.196:3307/jpatest?useSSL=false
    username: root
    password: 123456
  cache:
    type: redis
  mvc:
    view:
      suffix: .html
      prefix: /
  redis:
      host: 192.168.50.136
      port: 6379
      password:
      timeout: 5000
      jedis:
        pool:
          max-active: 8
          max-idle: 10
          max-wait: -1
          min-idle: 0
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081